#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
import setuptools

setup_params = dict(
	name='chucknorris',
	use_hg_version=True,
	author="YouGov",
	author_email="dev@YouGov.com",
	url="https://bitbucket.org/yougov/chucknorris",
	packages=setuptools.find_packages(),
	zip_safe=True,
	entry_points=dict(
		pmxbot_handlers={
			'Chuck Norris quips': 'chucknorris.pmxbot:init',
		}),
	setup_requires=[
		'hgtools',
	],
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
